"""
Cost of Living Comparator — City data (NYC = 100 baseline)
Product T10 for ClearMetric
"""

# 30 major US cities: overall, housing, groceries, transportation, healthcare, utilities
# Median rent 1BR / 2BR (approx 2024, USD)
CITY_DATA = {
    "New York": {
        "overall": 100,
        "housing": 100,
        "groceries": 100,
        "transportation": 100,
        "healthcare": 100,
        "utilities": 100,
        "rent_1br": 3800,
        "rent_2br": 4800,
    },
    "San Francisco": {
        "overall": 108,
        "housing": 125,
        "groceries": 105,
        "transportation": 95,
        "healthcare": 100,
        "utilities": 90,
        "rent_1br": 3200,
        "rent_2br": 4200,
    },
    "Los Angeles": {
        "overall": 92,
        "housing": 95,
        "groceries": 95,
        "transportation": 105,
        "healthcare": 95,
        "utilities": 95,
        "rent_1br": 2400,
        "rent_2br": 3200,
    },
    "Chicago": {
        "overall": 78,
        "housing": 72,
        "groceries": 88,
        "transportation": 95,
        "healthcare": 95,
        "utilities": 90,
        "rent_1br": 1900,
        "rent_2br": 2400,
    },
    "Houston": {
        "overall": 68,
        "housing": 55,
        "groceries": 82,
        "transportation": 85,
        "healthcare": 90,
        "utilities": 95,
        "rent_1br": 1200,
        "rent_2br": 1500,
    },
    "Phoenix": {
        "overall": 72,
        "housing": 65,
        "groceries": 85,
        "transportation": 90,
        "healthcare": 88,
        "utilities": 105,
        "rent_1br": 1400,
        "rent_2br": 1750,
    },
    "Philadelphia": {
        "overall": 75,
        "housing": 68,
        "groceries": 90,
        "transportation": 92,
        "healthcare": 95,
        "utilities": 95,
        "rent_1br": 1600,
        "rent_2br": 2000,
    },
    "San Antonio": {
        "overall": 65,
        "housing": 52,
        "groceries": 80,
        "transportation": 82,
        "healthcare": 88,
        "utilities": 95,
        "rent_1br": 1100,
        "rent_2br": 1400,
    },
    "San Diego": {
        "overall": 95,
        "housing": 105,
        "groceries": 98,
        "transportation": 95,
        "healthcare": 95,
        "utilities": 100,
        "rent_1br": 2300,
        "rent_2br": 2900,
    },
    "Dallas": {
        "overall": 70,
        "housing": 60,
        "groceries": 85,
        "transportation": 88,
        "healthcare": 90,
        "utilities": 95,
        "rent_1br": 1500,
        "rent_2br": 1900,
    },
    "Austin": {
        "overall": 78,
        "housing": 75,
        "groceries": 88,
        "transportation": 85,
        "healthcare": 90,
        "utilities": 95,
        "rent_1br": 1600,
        "rent_2br": 2000,
    },
    "Denver": {
        "overall": 88,
        "housing": 90,
        "groceries": 95,
        "transportation": 88,
        "healthcare": 95,
        "utilities": 85,
        "rent_1br": 1900,
        "rent_2br": 2400,
    },
    "Seattle": {
        "overall": 98,
        "housing": 105,
        "groceries": 102,
        "transportation": 95,
        "healthcare": 98,
        "utilities": 85,
        "rent_1br": 2200,
        "rent_2br": 2800,
    },
    "Boston": {
        "overall": 95,
        "housing": 98,
        "groceries": 102,
        "transportation": 92,
        "healthcare": 105,
        "utilities": 95,
        "rent_1br": 2600,
        "rent_2br": 3200,
    },
    "Nashville": {
        "overall": 75,
        "housing": 72,
        "groceries": 88,
        "transportation": 85,
        "healthcare": 92,
        "utilities": 90,
        "rent_1br": 1600,
        "rent_2br": 2000,
    },
    "Miami": {
        "overall": 82,
        "housing": 85,
        "groceries": 92,
        "transportation": 95,
        "healthcare": 90,
        "utilities": 100,
        "rent_1br": 2100,
        "rent_2br": 2700,
    },
    "Atlanta": {
        "overall": 72,
        "housing": 68,
        "groceries": 88,
        "transportation": 90,
        "healthcare": 92,
        "utilities": 95,
        "rent_1br": 1600,
        "rent_2br": 2000,
    },
    "Minneapolis": {
        "overall": 78,
        "housing": 72,
        "groceries": 92,
        "transportation": 88,
        "healthcare": 98,
        "utilities": 85,
        "rent_1br": 1500,
        "rent_2br": 1900,
    },
    "Portland OR": {
        "overall": 88,
        "housing": 88,
        "groceries": 98,
        "transportation": 92,
        "healthcare": 95,
        "utilities": 80,
        "rent_1br": 1800,
        "rent_2br": 2300,
    },
    "Charlotte": {
        "overall": 72,
        "housing": 68,
        "groceries": 88,
        "transportation": 88,
        "healthcare": 90,
        "utilities": 95,
        "rent_1br": 1500,
        "rent_2br": 1900,
    },
    "Raleigh": {
        "overall": 75,
        "housing": 72,
        "groceries": 88,
        "transportation": 85,
        "healthcare": 95,
        "utilities": 95,
        "rent_1br": 1500,
        "rent_2br": 1850,
    },
    "Indianapolis": {
        "overall": 65,
        "housing": 55,
        "groceries": 85,
        "transportation": 85,
        "healthcare": 92,
        "utilities": 95,
        "rent_1br": 1100,
        "rent_2br": 1400,
    },
    "Columbus OH": {
        "overall": 68,
        "housing": 58,
        "groceries": 85,
        "transportation": 85,
        "healthcare": 92,
        "utilities": 95,
        "rent_1br": 1200,
        "rent_2br": 1500,
    },
    "Salt Lake City": {
        "overall": 82,
        "housing": 82,
        "groceries": 92,
        "transportation": 85,
        "healthcare": 90,
        "utilities": 85,
        "rent_1br": 1500,
        "rent_2br": 1900,
    },
    "Tampa": {
        "overall": 75,
        "housing": 72,
        "groceries": 90,
        "transportation": 90,
        "healthcare": 90,
        "utilities": 100,
        "rent_1br": 1600,
        "rent_2br": 2000,
    },
    "Detroit": {
        "overall": 62,
        "housing": 45,
        "groceries": 85,
        "transportation": 95,
        "healthcare": 95,
        "utilities": 95,
        "rent_1br": 1100,
        "rent_2br": 1300,
    },
    "Pittsburgh": {
        "overall": 68,
        "housing": 58,
        "groceries": 88,
        "transportation": 88,
        "healthcare": 98,
        "utilities": 95,
        "rent_1br": 1200,
        "rent_2br": 1500,
    },
    "St Louis": {
        "overall": 62,
        "housing": 48,
        "groceries": 82,
        "transportation": 85,
        "healthcare": 92,
        "utilities": 95,
        "rent_1br": 1000,
        "rent_2br": 1300,
    },
    "Kansas City": {
        "overall": 65,
        "housing": 55,
        "groceries": 85,
        "transportation": 85,
        "healthcare": 92,
        "utilities": 95,
        "rent_1br": 1200,
        "rent_2br": 1500,
    },
    "Boise": {
        "overall": 78,
        "housing": 82,
        "groceries": 92,
        "transportation": 85,
        "healthcare": 88,
        "utilities": 85,
        "rent_1br": 1400,
        "rent_2br": 1750,
    },
}

# Lifestyle multipliers: fraction of salary for monthly budget (pre-tax)
LIFESTYLE_MULTIPLIERS = {
    "Frugal": 0.35,
    "Moderate": 0.45,
    "Comfortable": 0.55,
    "Luxury": 0.70,
}

# Household size adjustment (per-person cost scaling)
HOUSEHOLD_MULTIPLIERS = {
    1: 1.0,
    2: 1.6,
    3: 2.1,
    4: 2.6,
    5: 3.0,
    6: 3.4,
}

CITIES = sorted(CITY_DATA.keys())
CATEGORIES = ["housing", "groceries", "transportation", "healthcare", "utilities"]
RADAR_CATEGORIES = ["overall", "housing", "groceries", "transportation", "healthcare", "utilities"]
